# Generated by Django 5.0.6 on 2024-06-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perkuliahan', '0002_matakuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='jenjang',
            field=models.CharField(blank=True, choices=[('S1', 'STRATA-1'), ('S2', 'STRATA-2'), ('S3', 'STRATA-3'), ('D3', 'DIPLOMA-3'), ('D4', 'DIPLOMA-4')], max_length=150, null=True, verbose_name='Jenjang'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='email',
            field=models.EmailField(blank=True, help_text='contoh: admin@gmail.com', max_length=150, null=True, verbose_name='Email'),
        ),
    ]
